import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { askAdvisory, getAdvisoryThread, type AdvisoryThreadItem } from '../api/advisory';
import { describeApiError } from '../api/client';
import { Button } from './ui/Button';
import { Card } from './ui/Card';

// "Ask Aegis" — read-only advisory Q&A about this case, grounded in FRN's reference library + Board data.
// Decision support ONLY: the model gets no tools, can't change anything, the human is the overseer.
// Collapsed by default (just the cue) so it never clutters the sign-off screen; the Q&A thread is saved
// and re-renders when the case is reopened.

function ThreadEntry({ item }: { readonly item: AdvisoryThreadItem }) {
  return (
    <div className="rounded-md border border-slate-200 bg-slate-50 p-3">
      <div className="text-sm font-medium text-slate-800">Q: {item.question}</div>
      <div className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{item.answer}</div>
      {item.citations && item.citations.length > 0 ? (
        <div className="mt-2 text-xs text-slate-500">
          Sources:{' '}
          {item.citations.map((c, i) => (
            <span key={`${c.citation}-${i}`}>
              {i > 0 ? '; ' : ''}
              {c.citation}
              {c.letter_citable ? '' : ' (internal)'}
            </span>
          ))}
        </div>
      ) : null}
    </div>
  );
}

// `alwaysOpen` (Ryan 2026-06-13): on the dedicated "Ask Aegis" tab the Q&A opens immediately with no
// collapse + no card chrome (the tab IS the label). The physician sign-off page leaves it default
// (collapsible card) so it doesn't clutter the sign-off screen.
export function AdvisoryPanel({ caseId, alwaysOpen = false }: { readonly caseId: string; readonly alwaysOpen?: boolean }) {
  const qc = useQueryClient();
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const expanded = alwaysOpen || open;

  const thread = useQuery({
    queryKey: ['case', caseId, 'advisory-thread'],
    queryFn: () => getAdvisoryThread(caseId),
    enabled: expanded && caseId.length > 0,
  });

  const ask = useMutation({
    mutationFn: () => askAdvisory(caseId, question.trim()),
    onSuccess: async () => {
      setQuestion('');
      await qc.invalidateQueries({ queryKey: ['case', caseId, 'advisory-thread'] });
    },
    onError: (e: unknown) => window.alert(`Could not get an answer — ${describeApiError(e)}`),
  });

  function submit() {
    if (question.trim().length > 0 && !ask.isPending) ask.mutate();
  }

  const items = thread.data?.data ?? [];

  // The Q&A body — shared by both modes.
  const body = (
    <div className="space-y-4">
      {items.length > 0 ? (
        <div className="space-y-3">
          {items.map((it) => (
            <ThreadEntry key={it.id} item={it} />
          ))}
        </div>
      ) : thread.isLoading ? (
        <div className="text-sm text-slate-400">Loading…</div>
      ) : (
        <div className="text-sm text-slate-400">No questions yet — ask the first one below.</div>
      )}

      {ask.isPending ? <div className="text-sm text-slate-400">Aegis is thinking…</div> : null}

      <div>
        <textarea
          className="input h-24 w-full"
          placeholder="e.g. Is this OSA claim viable secondary to his service-connected PTSD?"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          // Enter submits; Shift+Enter inserts a newline (Ryan 2026-06-13).
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              submit();
            }
          }}
        />
        <div className="mt-2 flex items-center justify-between gap-3">
          <span className="text-[11px] text-slate-400">
            Generated by AI · use thoughtfully — verify before relying on any answer. Enter to send, Shift+Enter for a new line.
          </span>
          <Button type="button" variant="primary" loading={ask.isPending} disabled={question.trim().length === 0} onClick={submit}>
            Ask
          </Button>
        </div>
      </div>
    </div>
  );

  // Tab mode: open immediately, no card, no collapse.
  if (alwaysOpen) {
    return (
      <div className="space-y-3">
        <p className="text-sm text-slate-500">Decision-support Q&amp;A about this case — viability, framing, Board data. Read-only.</p>
        {body}
      </div>
    );
  }

  // Sign-off-page mode: collapsible card (avoids cluttering the sign-off screen).
  return (
    <Card className="rounded-lg border border-slate-200 bg-white shadow-sm">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between rounded-lg p-5 text-left hover:bg-slate-50"
      >
        <div>
          <h2 className="text-base font-semibold text-slate-900">Ask Aegis</h2>
          <p className="text-sm text-slate-500">Decision-support Q&amp;A about this case — viability, framing, Board data.</p>
        </div>
        <span className="text-xs text-slate-400">{open ? 'Hide ▲' : 'Open ▼'}</span>
      </button>
      {open ? <div className="border-t border-slate-100 p-5">{body}</div> : null}
    </Card>
  );
}
