import { describe, it, expect } from 'vitest';
import { classifyDocument } from '../documentClassifier.js';

describe('classifyDocument (content-based document naming)', () => {
  it('names a VA rating DECISION with condition + outcome (Woodley: GERD denied)', () => {
    const text = 'Department of Veterans Affairs ... Rating Decision 10/07/2025 ... REASONS FOR DECISION '
      + 'Service connection for gastrointestinal (also claimed as gastritis, GERD) is denied because ...';
    const r = classifyDocument({ filename: 'Woodley_GERD_Misc.pdf', text });
    expect(r.docType).toBe('va_rating_decision');
    expect(r.title).toBe('VA Rating Decision — GERD denied');
    expect(r.confidence).toBe('high');
  });

  it('names a granted rating decision with the outcome', () => {
    const text = 'RATING DECISION ... Service connection for tinnitus is granted with an evaluation of 10 percent ...';
    const r = classifyDocument({ filename: 'v7.pdf', text });
    expect(r.docType).toBe('va_rating_decision');
    expect(r.title).toBe('VA Rating Decision — tinnitus granted');
  });

  it('identifies a My HealtheVet / Blue Button export (the giant dump)', () => {
    const text = 'Report generated by My HealtheVet on VA.gov on January 20, 2026 Page 1 of 1119 ... Problem List ...';
    const r = classifyDocument({ filename: 'Misc_3.pdf', text });
    expect(r.docType).toBe('blue_button');
    expect(r.title).toBe('VA Blue Button (health record export)');
  });

  it('identifies a DD-214 by content and by filename', () => {
    expect(classifyDocument({ text: 'DD FORM 214 CERTIFICATE OF RELEASE OR DISCHARGE FROM ACTIVE DUTY' }).docType).toBe('dd214');
    expect(classifyDocument({ filename: 'Smith_dd214.pdf', text: 'nothing useful' }).docType).toBe('dd214');
  });

  it('identifies a sleep study', () => {
    const r = classifyDocument({ filename: 'Misc_2.pdf', text: 'POLYSOMNOGRAPHY REPORT. Apnea-Hypopnea Index (AHI): 42. Severe obstructive sleep apnea.' });
    expect(r.docType).toBe('sleep_study');
    expect(r.title).toBe('Sleep study');
  });

  it('names a DBQ with its condition', () => {
    const r = classifyDocument({ text: 'DISABILITY BENEFITS QUESTIONNAIRE — Sleep Apnea. Does the Veteran use a CPAP?' });
    expect(r.docType).toBe('dbq');
    expect(r.title).toBe('DBQ — OSA');
  });

  it('identifies a lay/buddy statement', () => {
    const r = classifyDocument({ text: 'STATEMENT IN SUPPORT OF CLAIM (VA Form 21-4138). I served with the veteran and witnessed ...' });
    expect(r.docType).toBe('lay_statement');
  });

  it('falls back to NO title (caller keeps filename) when nothing matches — "Misc" can still happen', () => {
    const r = classifyDocument({ filename: 'Misc_9.pdf', text: 'a page of unstructured notes with no recognizable VA signature' });
    expect(r.docType).toBe('other');
    expect(r.title).toBeNull();
  });

  it('is safe on empty/missing input', () => {
    expect(classifyDocument({}).docType).toBe('other');
    expect(classifyDocument({ filename: null, text: null }).title).toBeNull();
  });

  // Expanded coverage 2026-06-18 (Ryan: more content titles so fewer docs fall back to a filename).
  it('identifies an EGD / endoscopy report (+ condition)', () => {
    const r = classifyDocument({ text: 'ESOPHAGOGASTRODUODENOSCOPY (EGD). Findings: erosive esophagitis consistent with GERD.' });
    expect(r.docType).toBe('endoscopy');
    expect(r.title).toBe('Endoscopy report — GERD');
  });
  it('identifies a VA service-connected conditions list', () => {
    const r = classifyDocument({ text: 'Your service-connected disabilities and combined rating are listed below.' });
    expect(r.docType).toBe('sc_conditions_list');
    expect(r.title).toBe('VA service-connected conditions');
  });
  it('identifies an operative / procedure note', () => {
    const r = classifyDocument({ text: 'OPERATIVE REPORT. Preoperative diagnosis: ... Procedure performed: ...' });
    expect(r.docType).toBe('operative_note');
  });
  it('identifies an audiology / hearing test', () => {
    const r = classifyDocument({ text: 'Audiometry: pure tone average 35 dB. Speech recognition score 92%.' });
    expect(r.docType).toBe('audiology');
  });
});
